apiVersion : apps/v1
kind: Deployment
metadata:
  name: sukhwanpipelinesjavascriptdocker222 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sukhwanpipelinesjavascriptdocker222
  template:
    metadata:
      labels:
        app: sukhwanpipelinesjavascriptdocker222 
    spec:
      containers:
        - name: sukhwanpipelinesjavascriptdocker222 
          image: myakscr01.azurecr.io/sukhwanpipelinesjavascriptdocker222
          ports:
          - containerPort: 8080